import { fetchWithTimeout } from "../utils/fetchWithTimeout";
import type { MeetingLog } from "../interfaces/meetingLog";

const GENERIC_ERROR = "Something went wrong. Please try again.";

const authHeaders = (accessToken: string) => ({
  "Content-Type": "application/json",
  Authorization: `Bearer ${accessToken}`,
});

/** Fields accepted when creating a meeting log. `id` is a client-generated
 *  UUID (per the offline-sync rule) — generated by the caller
 *  (`useCreateMeetingLog`) rather than in here, so the offline queue knows
 *  the id before the write ever reaches the network, matching
 *  `apiTalks.ts`'s `CreateTalkInput`. */
export interface CreateMeetingLogInput {
  id: string;
  projectId: string;
  talkId?: string | null;
}

/**
 * POST /api/meetings — start a meeting log for a project. A retried create
 * with an id that already landed server-side 409s with a message the
 * offline queue's `flush()` recognizes as "already synced" rather than a
 * real failure — see `utils/db/outbox.ts`.
 */
export const createMeetingLog = async (
  accessToken: string,
  input: CreateMeetingLogInput,
): Promise<MeetingLog> => {
  const res = await fetchWithTimeout("/api/meetings", {
    method: "POST",
    headers: authHeaders(accessToken),
    body: JSON.stringify(input),
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data as MeetingLog;
};

/**
 * PUT /api/meetings/:meetingId/crew-photo — uploads the crew photo as a raw
 * binary body (not JSON, unlike every other call in this file), so the
 * `Content-Type` header carries the blob's actual mime type instead of
 * `application/json`. Idempotent server-side (Storage `upsert: true`) — a
 * retry or a retake always overwrites cleanly, no 409 case exists here.
 */
export const uploadCrewPhoto = async (
  accessToken: string,
  meetingId: string,
  blob: Blob,
): Promise<MeetingLog> => {
  const res = await fetchWithTimeout(`/api/meetings/${meetingId}/crew-photo`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": blob.type || "image/jpeg",
    },
    body: blob,
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data as MeetingLog;
};
