import { fetchWithTimeout } from "../utils/fetchWithTimeout";
import { PlanLimitError } from "../utils/PlanLimitError";
import type { MeetingLog } from "../interfaces/meetingLog";

const GENERIC_ERROR = "Something went wrong. Please try again.";
const DEFAULT_BUNDLE_FILENAME = "defense-bundle.zip";
// Longer than fetchWithTimeout's 10s default — assembling a ZIP means the
// server downloads and compresses one PDF per completed log before the first
// byte comes back, which can take a while for a company with a lot of history.
const BUNDLE_FETCH_TIMEOUT_MS = 60_000;

const authHeaders = (accessToken: string) => ({
  "Content-Type": "application/json",
  Authorization: `Bearer ${accessToken}`,
});

/** Fields accepted when creating a meeting log. `id` is a client-generated
 *  UUID (per the offline-sync rule) — generated by the caller
 *  (`useCreateMeetingLog`) rather than in here, so the offline queue knows
 *  the id before the write ever reaches the network, matching
 *  `apiTalks.ts`'s `CreateTalkInput`. */
export interface CreateMeetingLogInput {
  id: string;
  projectId: string;
  talkId?: string | null;
}

/**
 * POST /api/meetings — start a meeting log for a project. A retried create
 * with an id that already landed server-side 409s with a message the
 * offline queue's `flush()` recognizes as "already synced" rather than a
 * real failure — see `utils/db/outbox.ts`.
 */
export const createMeetingLog = async (
  accessToken: string,
  input: CreateMeetingLogInput,
): Promise<MeetingLog> => {
  const res = await fetchWithTimeout("/api/meetings", {
    method: "POST",
    headers: authHeaders(accessToken),
    body: JSON.stringify(input),
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data as MeetingLog;
};

/**
 * PATCH /api/meetings/:meetingId/complete — finalize a meeting once it has
 * >=1 signature. `heldAt` (an ISO timestamp for when the meeting was actually
 * held) is optional: when omitted — a completion queued by an older build —
 * this sends only the `Authorization` header and no body, and the server
 * falls back to its own receipt time. A retried complete against a meeting
 * that already landed 409s with a message the offline queue's `flush()`
 * recognizes as "already synced" rather than a real failure — see
 * `utils/db/outbox.ts`.
 */
export const completeMeeting = async (
  accessToken: string,
  meetingId: string,
  heldAt?: string,
): Promise<MeetingLog> => {
  const res = await fetchWithTimeout(`/api/meetings/${meetingId}/complete`, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      ...(heldAt && { "Content-Type": "application/json" }),
    },
    ...(heldAt && { body: JSON.stringify({ heldAt }) }),
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data as MeetingLog;
};

/**
 * PUT /api/meetings/:meetingId/crew-photo — uploads the crew photo as a raw
 * binary body (not JSON, unlike every other call in this file), so the
 * `Content-Type` header carries the blob's actual mime type instead of
 * `application/json`. Idempotent server-side (Storage `upsert: true`) — a
 * retry or a retake always overwrites cleanly, no 409 case exists here.
 */
export const uploadCrewPhoto = async (
  accessToken: string,
  meetingId: string,
  blob: Blob,
): Promise<MeetingLog> => {
  const res = await fetchWithTimeout(`/api/meetings/${meetingId}/crew-photo`, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": blob.type || "image/jpeg",
    },
    body: blob,
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data as MeetingLog;
};

/** Optional filters accepted by `GET /api/meetings`. `from`/`to` are ISO
 *  timestamps bounding when the meeting was held, `[from, to)`. */
export interface MeetingLogsFilters {
  projectId?: string;
  from?: string;
  to?: string;
}

/**
 * GET /api/meetings — the caller's company's meeting logs, newest first,
 * limited to the plan's history window. Pass `from`/`to` for one month of the
 * archive (completed meetings only).
 */
export const getMeetingLogs = async (
  accessToken: string,
  filters: MeetingLogsFilters = {},
): Promise<MeetingLog[]> => {
  const params = new URLSearchParams();
  if (filters.projectId) params.set("projectId", filters.projectId);
  if (filters.from) params.set("from", filters.from);
  if (filters.to) params.set("to", filters.to);
  const query = params.toString();

  const res = await fetchWithTimeout(
    `/api/meetings${query ? `?${query}` : ""}`,
    {
      method: "GET",
      headers: authHeaders(accessToken),
    },
  );

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data as MeetingLog[];
};

/** One archive month with at least one completed meeting. `month` is
 *  `YYYY-MM` in the viewer's local timezone. */
export interface MeetingMonth {
  month: string;
  count: number;
}

/** The result of `GET /api/meetings/months`: the month cards plus how many
 *  older logs the plan's history window hides (Free: 30 days). `historyDays`
 *  is null for plans with no window. */
export interface MeetingMonthsPage {
  months: MeetingMonth[];
  hiddenCount: number;
  historyDays: number | null;
}

/**
 * GET /api/meetings/months — one entry per month that has a completed
 * meeting, newest first. `tzOffset` (minutes, same sign as
 * `Date#getTimezoneOffset()`) is required; the server never guesses a
 * timezone. Rows outside the plan's history window are hidden, not deleted;
 * `hiddenCount` says how many so the UI can prompt an upgrade.
 */
export const getMeetingMonths = async (
  accessToken: string,
  tzOffset: number,
): Promise<MeetingMonthsPage> => {
  const res = await fetchWithTimeout(`/api/meetings/months?tzOffset=${tzOffset}`, {
    method: "GET",
    headers: authHeaders(accessToken),
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return {
    months: body.data as MeetingMonth[],
    hiddenCount: body.meta?.hiddenCount ?? 0,
    historyDays: body.meta?.historyDays ?? null,
  };
};

/** GET /api/meetings/:meetingId/pdf-url — a short-lived (5 minute) signed URL
 *  for the meeting's PDF. 404s if none was generated yet; 403s for a meeting
 *  outside the plan's history window. */
export const getMeetingPdfUrl = async (
  accessToken: string,
  meetingId: string,
): Promise<string> => {
  const res = await fetchWithTimeout(`/api/meetings/${meetingId}/pdf-url`, {
    method: "GET",
    headers: authHeaders(accessToken),
  });

  const body = await res.json().catch(() => null);

  if (!res.ok || !body?.success) {
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  return body.data.url as string;
};

/** GET /api/meetings/defense-bundle — the caller's own OSHA Defense Bundle: a
 *  streamed ZIP of every completed log this company has ever logged, not the
 *  usual `{ success, data }` JSON envelope (docs/sub-defense-bundle-design.md),
 *  so this can't reuse the `body?.success` unwrap every other call in this
 *  file uses. A 403 `PLAN_LIMIT` (Trade Free has no legal archive) throws a
 *  `PlanLimitError`, same as `apiGc.ts`'s version. The filename comes from
 *  the server's `Content-Disposition` header so the saved file matches what
 *  it named. */
export const getDefenseBundle = async (
  accessToken: string,
): Promise<{ blob: Blob; filename: string }> => {
  const res = await fetchWithTimeout(
    "/api/meetings/defense-bundle",
    { method: "GET", headers: { Authorization: `Bearer ${accessToken}` } },
    BUNDLE_FETCH_TIMEOUT_MS,
  );

  if (!res.ok) {
    const body = await res.json().catch(() => null);
    if (body?.data?.code === "PLAN_LIMIT") {
      throw new PlanLimitError(body.error ?? GENERIC_ERROR, body.data.limit ?? null);
    }
    throw new Error(body?.error ?? GENERIC_ERROR);
  }

  const disposition = res.headers.get("Content-Disposition") ?? "";
  const filename = disposition.match(/filename="([^"]+)"/)?.[1] ?? DEFAULT_BUNDLE_FILENAME;

  return { blob: await res.blob(), filename };
};
